#!/bin/bash
# run a python script in the local virtual env
if [ -f .python_env ]
then
    PYTHON_PATH=$(cat .python_env)
    PYTHON=$PYTHON_PATH/bin/python
else
    PYTHON=python
fi
echo "$PYTHON" $*
$PYTHON $*